version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: snyk
    versions:
    - 1.440.1
    - 1.440.4
    - 1.440.5
    - 1.445.0
    - 1.446.0
    - 1.448.0
    - 1.450.0
    - 1.452.0
    - 1.454.0
    - 1.455.0
    - 1.467.0
    - 1.471.0
    - 1.474.0
    - 1.476.0
    - 1.478.0
    - 1.483.0
    - 1.487.0
    - 1.489.0
    - 1.491.0
    - 1.495.0
    - 1.500.0
    - 1.503.0
    - 1.505.0
    - 1.509.0
    - 1.511.0
    - 1.514.0
    - 1.518.0
    - 1.521.0
    - 1.522.0
    - 1.526.0
    - 1.528.0
    - 1.529.0
    - 1.530.0
    - 1.533.0
    - 1.538.0
    - 1.541.0
    - 1.558.0
    - 1.563.0
    - 1.564.0
    - 1.566.0
    - 1.570.0
  - dependency-name: "@pulumi/pulumi"
    versions:
    - 2.19.0
    - 2.20.0
    - 2.21.0
    - 2.21.1
    - 2.21.2
    - 2.22.0
    - 2.23.1
    - 2.23.2
    - 2.24.1
    - 2.25.0
  - dependency-name: "@pulumi/aws"
    versions:
    - 3.25.1
    - 3.26.1
    - 3.27.0
    - 3.28.0
    - 3.28.1
    - 3.29.0
    - 3.29.1
    - 3.30.0
    - 3.30.1
    - 3.32.0
    - 3.32.1
    - 3.32.2
    - 3.33.0
    - 3.34.1
    - 3.34.2
    - 3.35.0
    - 3.36.0
    - 3.37.0
    - 3.38.0
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: typedoc
    versions:
    - 0.20.19
    - 0.20.20
    - 0.20.23
    - 0.20.24
    - 0.20.25
    - 0.20.29
    - 0.20.30
    - 0.20.32
    - 0.20.33
    - 0.20.34
    - 0.20.35
  - dependency-name: grpc
    versions:
    - 1.24.6
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
  - dependency-name: eslint-plugin-jsdoc
    versions:
    - 31.4.0
    - 31.6.0
    - 31.6.1
    - 32.0.0
    - 32.0.1
    - 32.0.2
    - 32.1.0
    - 32.1.1
    - 32.2.0
  - dependency-name: "@pulumi/kubernetes"
    versions:
    - 2.8.1
    - 2.8.2
  - dependency-name: marked
    versions:
    - 1.2.8
    - 1.2.9
    - 2.0.0
  - dependency-name: "@pulumi/gcp"
    versions:
    - 4.11.1
    - 4.12.0
  - dependency-name: tsutils
    versions:
    - 3.20.0
  - dependency-name: cross-env
    versions:
    - 7.0.3
  - dependency-name: "@pulumi/random"
    versions:
    - 3.0.3
  - dependency-name: "@pulumi/eks"
    versions:
    - 0.22.0
